config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'about', to: 'welcome#about'

  # get 'user', to: 'welcome#studentportal'
  get 'management', to: 'welcome#adminportal'
  get 'teacher', to: 'welcome#facultyportal'
  # get 'user', to: 'students#index'

  # get 'user', to: 'users#studentportal'
  # get 'teacher', to: 'faculties#index'
  # get 'management', to: 'welcome#adminportal'

  resources :users


  resources :students

  resources :students do
    member do
      get :confirm_email
    end
  end

  get 'student_login', to: 'student_sessions#new'
  post 'student_login', to: 'student_sessions#create'
  delete 'student_logout', to: 'student_sessions#destroy'

  get 'faculty_login', to: 'faculty_sessions#new'
  post 'faculty_login', to: 'faculty_sessions#create'
  delete 'faculty_logout', to: 'faculty_sessions#destroy'

  get 'admin_login', to: 'admin_sessions#new'
  post 'admin_login', to: 'admin_sessions#create'
  delete 'admin_logout', to: 'admin_sessions#destroy'

  resources :faculties

  get 'request_confirmation', to: 'requests#show'
  get 'requests', to: 'requests#index'
end

app/models/student.rb
class Student < ApplicationRecord
  before_create :confirmation_token
  before_save {self.email = email.downcase}

  NUMBER_REGEX = /\A\d+\z/

  validates :enrollnumber, presence: true,
            length: {mimumum:9, maximum: 11, message: "Enter a valid enrollment number(9-11 digits only) or,Enter the number without any leading zeroes"},
            uniqueness: true,
            format: {with: NUMBER_REGEX, message: "Only numbers should be entered in the specified field"}
  validates :firstname, presence: true,
            length: {minimum:4, maximum:30},
            uniqueness: {case_sensitive: false}
  validates :lastname, presence: true,
            length: {minimum:4, maximum:30}
  validates :branch, presence: true,
            length: {maximum: 50}
  validates :batch, presence: true,
            format: {with: NUMBER_REGEX, message: "Only numbers should be entered in the specified field"}

  validates :contact, presence: true,
            length: {is: 10},
            uniqueness: true,
            format: {with: NUMBER_REGEX, message: "Only numbers should be entered in the specified field"}

  VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
            uniqueness: {case_sensitive: false},
            length: {maximum: 105},
            format: {with: VALID_EMAIL_REGEX, message: "Enter a valid email address"}


  has_secure_password

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!
  end

private
    def confirmation_token
      if self.confirm_token.blank?
          self.confirm_token = SecureRandom.urlsafe_base64.to_s
      end
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  require 'resolv-replace'
  before_action :set_student, only: [:edit, :update, :show, :destroy]
  before_action :require_user, only: [:edit, :index, :show]
  before_action :require_same_student, only: [:edit, :update, :destroy]

  def index
    @students = Student.paginate(:page => params[:page], per_page: 5)
  end

  def new
    if !logged_in? or admin_logged_in?
      @student = Student.new
    else
      flash[:danger] = "You cannot register as a new student while logged in."
      redirect_to root_path
    end
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      if admin_logged_in?
        flash[:success] = "New Student has been registered to the Smart-ID Database."
        redirect_to root_path
      else
         session[:student_id] = @student.id
        # UserMailer.registration_confirmation(@student).deliver
      #  flash[:primary] = "Hi #{@student.firstname}, An email has been sent to your registered email-id. Confirm your email to continue"
         flash[:success] = "Welcome #{@student.firstname + " " + @student.lastname} to the portal"
        redirect_to students_path
      end
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @student.update(student_params)
      flash[:success] = "Student Profile was updated successfully."
      redirect_to student_path(@student)
    else
      render 'edit'
    end
  end

  def destroy
    session[:student_id] = nil
    @student.destroy
    flash[:danger] = "Student profile was succesfully deleted."
    redirect_to students_path
  end

  def confirm_email
    student = Student.find_by_confirm_token(params[:id])
    if student
      student.email_activate
      flash[:success] = "Welcome to the Student Portal! Your email has been confirmed.
      Please sign in to continue."
      redirect_to student_login_path
    else
      flash[:danger] = "Sorry. User does not exist"
      redirect_to root_path
    end
  end

  private

    def student_params
      params.require(:student).permit(:enrollnumber, :firstname, :lastname, :branch, :batch, :contact, :email, :password)
    end

    def set_student
      @student = Student.find(params[:id])
    end

    def require_same_student
      if current_student != @student and !admin_logged_in?
        flash[:danger] = "You can only edit or update your profile"
        redirect_to root_path
      end
    end

end

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student%>

<div class="jumbotron">

<%= form_for(@student, :html => {class: "horizontal", role: "form"}) do |f| %>
<div class= "form-group">
  <div class= "control-label">
    <%= f.label :"Enrollment Number"%>
    </div>

    <%= f.text_field :enrollnumber, class: "form-control", placeholder: "Enter your Enrollment Number", autofocus: true %>
</div>
<div class= "form-group">
  <div class= "control-label">
    <%= f.label :"First Name"%>
        </div>

    <%= f.text_field :firstname, class: "form-control", placeholder: "Enter your First Name", autofocus: true%>
</div>
<div class= "form-group">
  <div class= "control-label">
    <%= f.label :"Last Name"%>
        </div>
    <%= f.text_field :lastname, class: "form-control", placeholder: "Enter your Last Name", autofocus: true%>
</div>
<div class= "form-group">
  <div class= "control-label">
    <%= f.label :Branch%>
        </div>
    <%= f.text_field :branch, class: "form-control", placeholder: "Enter your Branch", autofocus: true%>
</div>
<div class= "form-group">
  <div class= "control-label">
    <%= f.label :Batch%>
        </div>
    <%= f.text_field :batch, class: "form-control", placeholder: "Enter your Batch", autofocus: true%>
</div>
<div class= "form-group">
  <div class= "control-label">
    <%= f.label :Contact%>
        </div>
    <%= f.text_field :contact, class: "form-control", placeholder: "Enter your Contact Number", autofocus: true%>
</div>
<div class= "form-group">
  <div class= "control-label">
    <%= f.label :email%>
        </div>
    <%= f.email_field :email, class: "form-control", placeholder: "Enter your Email Address", autofocus: true%>
</div>
<% if !student_logged_in? %>
<div class="form-group">
  <div class= "control-label">
    <%= f.label :password%>
        </div>
    <%= f.password_field :password, class: "form-control", placeholder: "Enter Password", autofocus: true%>
</div>
<% end %>
<br>
    <%= f.submit(@student.new_record? ? "Register" : "Update Account", class:"btn btn-lg btn-primary but")%>
<% end %>
</div>

app/views/students/edit.html.erb
<h2 class="head2">Edit your profile</h2>
<%= render 'form' %>

app/views/students/index.html.erb
<div class="container">
<h2 class="head2"> All Students registered for Smart-ID</h2>
<% if student_logged_in? %>
<div class="hd">
  <% if !(Smartid.find_by(:registration_number => (Student.find(session[:student_id])).enrollnumber)) %>
    <%= link_to 'Request for Smart-ID(Card Issue)', '#', class: "btn btn-success" %>
  <% end %>
</div>
<% end %>
<br/>
<table class="table">
  <tbody>
  <% @students.each do |student| %>
   <% if student_logged_in? && current_student.enrollnumber == student.enrollnumber%>
    <tr>
      <td><%= link_to (gravatar_for student), student_path(student) %></td>
      <td><%=student.enrollnumber.to_s.rjust(11,'0')%></td>
      <td><%=student.firstname+" "+student.lastname%></td>
      <td><%=student.branch%></td>
      <td><%=student.batch%></td>
      <td><%=student.contact%></td>

        <td> <%= link_to 'Smart-ID(Student)', user_path(student), class: "btn btn-primary" %></td>
    <% elsif admin_logged_in?%>
       <td><%= link_to (gravatar_for student), student_path(student) %></td>
      <td><%=student.enrollnumber.to_s.rjust(11,'0')%></td>
      <td><%=student.firstname+" "+student.lastname%></td>
      <td><%=student.branch%></td>
      <td><%=student.batch%></td>
      <td><%=student.contact%></td>
    <td><%= link_to "Edit", edit_student_path(student), class: "btn btn-primary"%></td>
    <td><%=link_to 'Delete', student_path(student), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"%></td>
    <td><%= link_to 'Requests', '#'%></td>
    </tr>
  <% end %>
  <% end %>
  </tbody>
</table>
<%= will_paginate @students, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/students/new.html.erb

<h2 class="head2">The New Student Registration Page</h2>
<%= render 'form' %>
<br>

app/views/students/show.html.erb
<h2 class="head2">
  <%= @student.firstname+" "+@student.lastname%>'s Profile
</h2><br>
<div id="box-container">
    <div id="box-1">
  <h2><%= gravatar_for @student , size: 150%></h2> 
  <div class="roll"><b><%= @student.enrollnumber%></b></div>
  </div>
  <div id="box-2">
    <table class="table">
    <tr><th>NAME</th> <td><%= @student.firstname+" "+@student.lastname%></td></tr>
    <tr><th>Branch</th> <td> <%= @student.branch%></td></tr>
    <tr><th>Batch</th> <td> <%= @student.batch%></td></tr>
  <tr><th>Contact</th> <td> <%= @student.contact%></td></tr>
</table>
</div>
</div>
<div class="tabs">
   <%= link_to "Students", students_path, class: "btn btn-primary", align: "center" %>
   <%= link_to 'Smart-ID', user_path(@student), class: "btn btn-primary" %>
    <% if admin_logged_in?%>
    <%= link_to "Edit", edit_student_path(@student), class: "btn btn-secondary" %>
    <%= link_to "Delete", student_path(@student), method: :delete, data: {confirm: "Are you sure?"},class: "btn btn-danger", align: "center"  %> 
    <% end %>
</div>
<br>