config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'about', to: 'welcome#about'

  # get 'user', to: 'welcome#studentportal'
  get 'management', to: 'welcome#adminportal'
  get 'teacher', to: 'welcome#facultyportal'
  # get 'user', to: 'students#index'

  # get 'user', to: 'users#studentportal'
  # get 'teacher', to: 'faculties#index'
  # get 'management', to: 'welcome#adminportal'

  resources :users


  resources :students

  resources :students do
    member do
      get :confirm_email
    end
  end

  get 'student_login', to: 'student_sessions#new'
  post 'student_login', to: 'student_sessions#create'
  delete 'student_logout', to: 'student_sessions#destroy'

  get 'faculty_login', to: 'faculty_sessions#new'
  post 'faculty_login', to: 'faculty_sessions#create'
  delete 'faculty_logout', to: 'faculty_sessions#destroy'

  get 'admin_login', to: 'admin_sessions#new'
  post 'admin_login', to: 'admin_sessions#create'
  delete 'admin_logout', to: 'admin_sessions#destroy'

  resources :faculties

  get 'request_confirmation', to: 'requests#show'
  get 'requests', to: 'requests#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end


  def about
  end

  def studentportal

  end

  def facultyportal

  end

  def adminportal

  end

end

app/views/welcome/_about.html.erb
<!-- Header -->
<header class="text-center">
  <br>
</header>
      <div class="card border-0 shadow">
       <img src="https://img.collegepravesh.com/2017/02/BPIT-Delhi.jpg" height="300" class="card-img-top" alt="...">
        <div class="card-body text-center">
          <h5 class="card-title mb-0">
Smart-ID is a campus-wide project, prepared by students of Bhagwan Parshuram Institute ofTechnology
to facilitate and aid students as well as faculty members in their day to day life on campus.
It's Primary aim is to digitize all sorts of transactions made inside the campus and reduce the burden on students to carry
 cash etc. Students won't even need to carry other documents like College ID Card, Library Card etc. as one Smart-ID will be enough.
 </div>
 </div>
 <br><br>
<!-- Page Content -->
<div class="container">
  <div class="row">
    <!-- Team Member 1 -->
    <div class="col-xl-6 col-md-6 mb-4">
      <div class="card border-0 shadow">
               <div class="card-body text-center">
          <h5 class="card-title mb-0">Are you a Student?</h5>
          <div class="card-text text-black-50">Then get yourself <%= link_to "registered with the Student Portal", new_student_path %>. If you already have an account then <%= link_to "login to the student portal", student_login_path %>, click on 'register for Smart-ID' and provide your Enrolment Number. Soon you'll get your Smart-ID Card and your Smart-ID portal will be enabled.</div>
        </div>
      </div>
    </div>
    <!-- Team Member 2 -->
    <div class="col-xl-6 col-md-6 mb-4">
      <div class="card border-0 shadow">
        <div class="card-body text-center">
          <h5 class="card-title mb-0">Are you a Faculty Member?
</h5>
          <div class="card-text text-black-50">Then get yourself <%= link_to "registered with the Faculty Portal", new_faculty_path %>. Once registered, <%= link_to "login to the faculty portal", faculty_login_path %> and click on 'register for Smart-ID', provide your Details and once the adminstrator processes your request, a Smart-ID Card will be issued to you. Now you can add money to your Smart-ID Wallet, view your balance and transaction history on the Smart-ID Portal.</div>
        </div>
      </div>
    </div>
  <!-- /.row -->
</div>
</div>
<!-- /.container -->

app/views/welcome/adminportal.html.erb
<h1 align="center">Portal for Administration</h1>

app/views/welcome/facultyportal.html.erb
<h1 align="center">Portal for Faculty</h1>

app/views/welcome/home.html.erb

<div class="container">
  <!-- /Important Notice  --> 
	<section id="important-notice">
		<div class="container">
			<div class="row alert alert-success">
				<div class="col-md-2"><h5>News Flash:</h5></div>
				<div class="col-md-10">
					<marquee class="text-danger">
					The Bhagwan Parshuram Institute of Technology is getting it's own Smart-ID System. Avail your Smart-ID Card NOW!
					</marquee>
					
				</div>
			</div>
		</div>
	</section>
<!-- <div class="jumbotron cent">
  <h1 class="cent title">SMART-ID</h1>
<% if logged_in? %>
  <%= link_to 'Students', students_path, class: "btn btn-primary btn-lg" %> | <%= link_to 'Faculty', faculties_path, class: "btn btn-primary btn-lg" %>
<% else %>
    <span>
      <a class="dropdown-toggle btn btn-primary btn-lg" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Register
      </a>
      <div class="dropdown-menu">
        <%= link_to 'As Student', new_student_path, class: "dropdown-item" %>
        <%= link_to 'As Faculty', new_faculty_path, class: "dropdown-item" %>
      </div>
    </span>
    <span>
      <a class="dropdown-toggle btn btn-lg butt btn-primary" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Login
      </a>
      <div class="dropdown-menu">
        <%= link_to 'As Student', student_login_path, class: "dropdown-item" %>
        <%= link_to 'As Faculty', faculty_login_path, class: "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to 'Admin', admin_login_path, class: "dropdown-item" %>
      </div>
    </span>
<% end %>
</div> -->
<header> <h1> SMART-ID</h1></header> <br>
<% if logged_in? %>
 <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100 carry" src="https://img.theculturetrip.com/768x432/wp-content/uploads/2018/05/shutterstock_1097144396.jpg" alt="First slide">
   <div class="carousel-caption d-none d-md-block c1">
   <div class="cap"> <h2 >Say no to tedious cash transactions with our Smart-ID Solutions</h2></div>
 <a><%= link_to 'Students', students_path, class: "btn btn-primary btn-lg" %> | <%= link_to 'Faculty', faculties_path, class: "btn btn-primary btn-lg" %></a>
    </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 carry" src="https://travel.jumia.com/blog/ng/wp-content/uploads/2015/10/waiting-660x400.jpg" alt="Second slide">
     <div class="carousel-caption c2 d-none d-md-block">
   <div class="cap"><h2>No need to wait in long ATM Queues just use our Smart-ID Card for Campus Transactions</h2></div>
   <a><%= link_to 'Students', students_path, class: "btn btn-primary btn-lg" %> | <%= link_to 'Faculty', faculties_path, class: "btn btn-primary btn-lg" %></a>
    </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 carry" src="https://socialmediaexplorer.com/wp-content/uploads/2019/01/Photo.jpg" alt="Third slide">
     <div class="carousel-caption c3 d-none d-md-block">
   <div class="cap"><h2>Become more eco friendly by saying be bye to paper based attendance system</h2></div>
  <a><%= link_to 'Students', students_path, class: "btn btn-primary btn-lg" %> | <%= link_to 'Faculty', faculties_path, class: "btn btn-primary btn-lg" %></a>
    </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    prev<span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    Next<span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<% else %>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100 carry" src="https://img.theculturetrip.com/768x432/wp-content/uploads/2018/05/shutterstock_1097144396.jpg" alt="First slide">
   <div class="carousel-caption d-none d-md-block c1">
   <div class="cap"> <h2 >Say no to tedious cash transactions with our Smart-ID Solutions</h2></div>
  <span>
      <a class="dropdown-toggle btn btn-primary btn-lg" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Register
      </a>
      <div class="dropdown-menu">
        <%= link_to 'As Student', new_student_path, class: "dropdown-item" %>
        <%= link_to 'As Faculty', new_faculty_path, class: "dropdown-item" %>
      </div>
    </span>
    <span>
      <a class="dropdown-toggle btn btn-lg butt btn-primary" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Login
      </a>
      <div class="dropdown-menu">
        <%= link_to 'As Student', student_login_path, class: "dropdown-item" %>
        <%= link_to 'As Faculty', faculty_login_path, class: "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to 'Admin', admin_login_path, class: "dropdown-item" %>
      </div>
    </span>
    </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 carry" src="https://travel.jumia.com/blog/ng/wp-content/uploads/2015/10/waiting-660x400.jpg" alt="Second slide">
     <div class="carousel-caption c2 d-none d-md-block">
   <div class="cap"><h2>No need to wait in long ATM Queues just use our Smart-ID Card for Campus Transactions</h2></div>
  <span>
      <a class="dropdown-toggle btn btn-primary btn-lg" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Register
      </a>
      <div class="dropdown-menu">
        <%= link_to 'As Student', new_student_path, class: "dropdown-item" %>
        <%= link_to 'As Faculty', new_faculty_path, class: "dropdown-item" %>
      </div>
    </span>
    <span>
      <a class="dropdown-toggle btn btn-lg butt btn-primary" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Login
      </a>
      <div class="dropdown-menu">
        <%= link_to 'As Student', student_login_path, class: "dropdown-item" %>
        <%= link_to 'As Faculty', faculty_login_path, class: "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to 'Admin', admin_login_path, class: "dropdown-item" %>
      </div>
    </span>
    </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 carry" src="https://socialmediaexplorer.com/wp-content/uploads/2019/01/Photo.jpg" alt="Third slide">
     <div class="carousel-caption c3 d-none d-md-block">
   <div class="cap"><h2>Become more eco friendly by saying be bye to paper based attendance system</h2></div>
  <span>
      <a class="dropdown-toggle btn btn-primary btn-lg" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Register
      </a>
      <div class="dropdown-menu">
        <%= link_to 'As Student', new_student_path, class: "dropdown-item" %>
        <%= link_to 'As Faculty', new_faculty_path, class: "dropdown-item" %>
      </div>
    </span>
    <span>
      <a class="dropdown-toggle btn btn-lg butt btn-primary" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Login
      </a>
      <div class="dropdown-menu">
        <%= link_to 'As Student', student_login_path, class: "dropdown-item" %>
        <%= link_to 'As Faculty', faculty_login_path, class: "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to 'Admin', admin_login_path, class: "dropdown-item" %>
      </div>
    </span>
    </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    prev<span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    Next<span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<% end %>
<br>
<br>
<div class="aboutt"><h2>About US</h2>
</div>
<br>
<br>
<div class="test">
<%= render 'welcome/about' %>
<div id="about"> </div>
</div>
</div>