config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'about', to: 'welcome#about'

  # get 'user', to: 'welcome#studentportal'
  get 'management', to: 'welcome#adminportal'
  get 'teacher', to: 'welcome#facultyportal'
  # get 'user', to: 'students#index'

  # get 'user', to: 'users#studentportal'
  # get 'teacher', to: 'faculties#index'
  # get 'management', to: 'welcome#adminportal'

  resources :users


  resources :students

  resources :students do
    member do
      get :confirm_email
    end
  end

  get 'student_login', to: 'student_sessions#new'
  post 'student_login', to: 'student_sessions#create'
  delete 'student_logout', to: 'student_sessions#destroy'

  get 'faculty_login', to: 'faculty_sessions#new'
  post 'faculty_login', to: 'faculty_sessions#create'
  delete 'faculty_logout', to: 'faculty_sessions#destroy'

  get 'admin_login', to: 'admin_sessions#new'
  post 'admin_login', to: 'admin_sessions#create'
  delete 'admin_logout', to: 'admin_sessions#destroy'

  resources :faculties

  get 'request_confirmation', to: 'requests#show'
  get 'requests', to: 'requests#index'
end

app/views/layouts/_footer.html.erb
    <div class="footer">
        <hr>
        <small><div class="text-primary cent">
           <b>Copyright &copy;</b> of JKSN Pvt. Ltd.
        </div></small>
    </div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<div class='alert alert-<%="#{name}" %>'>
  <a href="#" class="close" data-dismiss="alert">&#215;</a>
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark bg-dark">
  <%= link_to "Smart-ID", root_path, class: "navbar-brand logo" %>

    <% if logged_in? %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if student_logged_in? %>
            <em><b><%= current_student.firstname+" "+current_student.lastname %>(Student)</b></em>
          <% elsif faculty_logged_in? %>
            <em><b><%= current_faculty.firstname+" "+current_faculty.lastname + "(#{current_faculty.designation})"%></b></em>
          <% else %>
            <em><b><%= current_admin.firstname+" "+current_admin.lastname %> (Admin)</b></em>
           <% end %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if student_logged_in? %>
            <%= link_to 'Edit Your Profile', edit_student_path(current_student), class: "dropdown-item" %>
            <%= link_to 'View Your profile', student_path(current_student), class: "dropdown-item" %>
          <% elsif faculty_logged_in? %>
            <%= link_to 'Edit Your Profile', edit_faculty_path(current_faculty), class: "dropdown-item" %>
            <%= link_to 'View Your profile', faculty_path(current_faculty), class: "dropdown-item" %>

           <% else %>
            <%= link_to 'New student', new_student_path, class: "dropdown-item"%>
            <%= link_to 'New Faculty', new_faculty_path, class: "dropdown-item"%>
            
          <% end %>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav navbar-right">
      <li class="nav-item active">
    <% if student_logged_in? %>
    <em> <%= link_to "Logout", student_logout_path, method: :delete, class: "nav-link" %></em>
    <% elsif faculty_logged_in? %>
     <em><%= link_to "Logout", faculty_logout_path, method: :delete, class: "nav-link" %></em>
    <% else %>
     <em><%= link_to "Logout", admin_logout_path, method: :delete, class: "nav-link" %></em>
       <% end %>
      </li>
      </ul>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartId</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <br><br><br><br>
    <div class="container">
      <br>
    <%= render 'layouts/messages' %>
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>